#include "runtime/dsl/compiled_ops.h"

#include <algorithm>
#include <cstdio>
#include <limits>
#include <stdexcept>
#include <vector>

#include "runtime/dsl/compiled_ops_helpers.h"
#include "runtime/dsl/graph_executor_utils.h"
#include "kernels/kernels.h"
#include "utilities/dtype.h"

namespace dsl {

void CompiledExecutor::dispatch_add(const CompiledOp& op) {
    Tensor& a = resolve_tensor(op.inputs[0]);
    Tensor& b = resolve_tensor(op.inputs[1]);
    Tensor& out = ensure_output_tensor(op.outputs[0]);

    // Backward accumulation outputs may lack shape info (e.g., d_*_accum_N tensors
    // generated by autodiff for multi-use gradient accumulation).  For element-wise
    // add the output shape always matches the inputs, so reallocate with correct shape.
    if (out.nelem() != a.nelem() && a.Rank > 0) {
        std::vector<long> shape(a.Sizes.begin(), a.Sizes.begin() + a.Rank);
        out = mRunState.temp_alloc(a.DType, shape);
        fill_zero(out, mRunState.MainStream);
        mTemps.push_back(out);
    }

    vector_add_sr(out, a, b, 1.0f, static_cast<long>(a.nelem()), 0, mRunState.MainStream);
}

void CompiledExecutor::dispatch_add_backward(const CompiledOp& op) {
    // Addition backward: gradients pass through unchanged to both inputs
    Tensor& d_out = resolve_tensor(op.inputs[0]);

    // For pre-allocated gradient slots (like d_res_ffn, d_res_att), we must copy the
    // upstream gradient into the original simplified_grads buffer. Simply aliasing
    // the data pointer causes shared storage between residual and branch gradients,
    // which breaks LoRA (it does in-place dx accumulation).
    // IMPORTANT: We must get the base tensor directly from simplified_grads(), not via
    // resolve_tensor(), because resolve_tensor() may return a cached view from mTensors.
    auto assign_output = [&](const TensorRef& ref) {
        if (!ref.name.empty()) {
            if (auto base = base_param_from_grad(ref.name)) {
                bool accumulate = mAccumulateTensors.count(ref.name) > 0;
                if (!accumulate) {
                    accumulate = mAccumulateTensors.count("d_" + *base) > 0;
                }
                bool grad_accum = false;
                if (Tensor* grad = mGrads.get_param_grad(*base, grad_accum)) {
                    if (grad->Data) {
                        Tensor target = ref.shape.empty() ? *grad : view_tensor(*grad, ref.shape);
                        if (target.DType != d_out.DType) {
                            throw std::runtime_error("dispatch_add_backward: dtype mismatch for " + ref.name);
                        }
                        if (target.nelem() != d_out.nelem()) {
                            throw std::runtime_error("dispatch_add_backward: shape mismatch for " + ref.name);
                        }
                        if (target.Data != d_out.Data) {
                            if (accumulate) {
                                vector_add_sr(target, target, d_out, 1.0f,
                                              static_cast<long>(target.nelem()), 0, mRunState.MainStream);
                            } else {
                                CUDA_CHECK(cudaMemcpyAsync(target.Data, d_out.Data, target.bytes(),
                                                           cudaMemcpyDeviceToDevice, mRunState.MainStream));
                            }
                        }
                        store_tensor(ref, target);
                        return;
                    }
                }
            }
        }

        Tensor* base_grad = nullptr;
        if (ref.layer_idx >= 0) {
            auto& grads = mRunState.simplified_grads(ref.layer_idx);
            switch (ref.slot) {
                case TensorSlot::BlockDResFFN: base_grad = &grads.d_res_ffn; break;
                case TensorSlot::BlockDResAtt: base_grad = &grads.d_res_att; break;
                case TensorSlot::BlockDAttOut: base_grad = &grads.d_att_out; break;
                case TensorSlot::BlockDLN1: base_grad = &grads.d_ln1; break;
                case TensorSlot::BlockDLN2: base_grad = &grads.d_ln2; break;
                case TensorSlot::BlockDSwiGLU: base_grad = &grads.d_swiglu; break;
                case TensorSlot::BlockDAtt: base_grad = &grads.d_att; break;
                case TensorSlot::BlockDQKV: base_grad = &grads.d_qkv; break;
                case TensorSlot::BlockDMLPUp: base_grad = &grads.d_mlp_up; break;
                case TensorSlot::BlockDMLPDown: base_grad = &grads.d_mlp_down; break;
                default: break;
            }
        }

        if (base_grad) {
            if (base_grad->Data) {
                if (base_grad->DType != d_out.DType) {
                    throw std::runtime_error("dispatch_add_backward: dtype mismatch for " + ref.name);
                }
                if (base_grad->Data != d_out.Data) {
                    CUDA_CHECK(cudaMemcpyAsync(base_grad->Data, d_out.Data, d_out.bytes(),
                                               cudaMemcpyDeviceToDevice, mRunState.MainStream));
                }
                store_tensor(ref, view_tensor(*base_grad, ref.shape));
                return;
            }
            // For stack-allocated gradient temps, allocate proper storage instead of aliasing.
            // Aliasing to d_out can cause stale memory access when the stack is restored at
            // layer boundaries because the aliased memory gets recycled.
            const bool is_stack_grad = mRunState.large_bwd_temps_on_stack() &&
                (ref.slot == TensorSlot::BlockDQKV ||
                 ref.slot == TensorSlot::BlockDMLPUp ||
                 ref.slot == TensorSlot::BlockDSwiGLU);
            if (is_stack_grad) {
                // Allocate proper stack storage and copy data
                mRunState.temp_acquire(*base_grad);
                mTemps.push_back(*base_grad);
                CUDA_CHECK(cudaMemcpyAsync(base_grad->Data, d_out.Data, d_out.bytes(),
                                           cudaMemcpyDeviceToDevice, mRunState.MainStream));
                store_tensor(ref, view_tensor(*base_grad, ref.shape));
                return;
            }
            // Fall back to aliasing if the base grad has no storage yet (non-stack temps).
            base_grad->Data = d_out.Data;
            store_tensor(ref, view_tensor(*base_grad, ref.shape));
            return;
        }
        // Default: just expose d_out as-is.
        store_tensor(ref, d_out);
    };

    assign_output(op.outputs[0]);
    if (op.outputs.size() > 1) {
        assign_output(op.outputs[1]);
    }
}


}  // namespace dsl
