apiVersion: v1
kind: PersistentVolume
metadata:
  name: lakefs-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/lakefs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lakefs-pvc
  namespace: lakefs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Ti
