image: 
  repository: nvcr.io/nvidia/k8s/dcgm-exporter
  tag: 4.3.1-4.4.1-ubuntu22.04

runtimeClassName: nvidia

tolerations: []

# excludee any node with the node-role.kubernetes.io/control-plane label 
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist

extraEnv:
  - name: DCGM_EXPORTER_INTERVAL
    value: "5000"  # in milliseconds
  - name: NVIDIA_VISIBLE_DEVICES
    value: "all"

serviceMonitor:
  enabled: false

customMetrics: |
    # General
    DCGM_FI_DEV_COUNT, counter, Number of GPUs in the system.
    DCGM_FI_DEV_NAME, label, Name of the GPU.

    # Memory
    DCGM_FI_DEV_FB_TOTAL, counter, Total framebuffer memory (in Mb).
    DCGM_FI_DEV_FB_FREE, counter, Free framebuffer memory (in Mb).
    DCGM_FI_DEV_FB_USED, counter, Used framebuffer memory (in Mb).
    DCGM_FI_DEV_FB_RESERVED, counter, Reserved framebuffer memory (in Mb).

    # Temperature
    DCGM_FI_DEV_MEMORY_TEMP, gauge, Memory temperature (in C).
    DCGM_FI_DEV_GPU_TEMP,    gauge, GPU temperature (in C).

    # Power
    DCGM_FI_DEV_POWER_USAGE,              gauge, Power draw (in W).
    DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION, counter, Total energy consumption since boot (in mJ).

    # Utilization (the sample period varies depending on the product)
    DCGM_FI_DEV_GPU_UTIL,      gauge, GPU utilization (in %).
    DCGM_FI_DEV_MEM_COPY_UTIL, gauge, Memory utilization (in %).
