# Disable scraping of components that k3s bundles or doesn't use in standard ways.
# This prevents constant "TargetDown" alerts in Alertmanager.
kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

# Prometheus Configuration
prometheus:
  prometheusSpec:
    retention: 1h
    # Leverage the default k3s local-path storage class
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

# Grafana Configuration
grafana:
  enabled: false

# Alertmanager Configuration
alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi