# GRPO Orchestrator Example

model:
  name: "./reverse-text-qwen3-2"
  lora_adapter: "default"
  lora_rank: 16
  lora_alpha: 32

env:
  - id: reverse-text

batch_size: 128
rollouts_per_example: 16
seq_len: 2048
max_steps: 20
use_token_client: false

sampling:
  max_tokens: 128

client:
  base_url: 
    - http://localhost:8007/v1
