apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-https-redirect
  namespace: kube-system
spec:
  redirectRegex:
    regex: "^http://(.*)"
    replacement: "https://$1"
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-secure-headers
  namespace: kube-system
spec:
  headers:
    contentSecurityPolicy: >
      default-src 'self' 'unsafe-inline' 'unsafe-eval' *;
      img-src 'self' blob: data:;
      font-src 'self';
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-ssl-headers
  namespace: kube-system
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
---
kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: traefik-console
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.k8s.localhost`)
      services:
        - kind: TraefikService
          name: api@internal
