from transformers import FineGrainedFP8Config, Qwen3_5ForConditionalGeneration

model_name = "Qwen/Qwen3.5-9B"
quantization_config = FineGrainedFP8Config(modules_to_not_convert=[
    "lm_head",
    "language_model.embed_tokens",
    "language_model.layers.0.linear_attn.conv1d",
    "language_model.layers.0.linear_attn.in_proj_a",
    "language_model.layers.0.linear_attn.in_proj_b",
    "language_model.layers.1.linear_attn.conv1d",
    "language_model.layers.1.linear_attn.in_proj_a",
    "language_model.layers.1.linear_attn.in_proj_b",
    "language_model.layers.10.linear_attn.conv1d",
    "language_model.layers.10.linear_attn.in_proj_a",
    "language_model.layers.10.linear_attn.in_proj_b",
    "language_model.layers.12.linear_attn.conv1d",
    "language_model.layers.12.linear_attn.in_proj_a",
    "language_model.layers.12.linear_attn.in_proj_b",
    "language_model.layers.13.linear_attn.conv1d",
    "language_model.layers.13.linear_attn.in_proj_a",
    "language_model.layers.13.linear_attn.in_proj_b",
    "language_model.layers.14.linear_attn.conv1d",
    "language_model.layers.14.linear_attn.in_proj_a",
    "language_model.layers.14.linear_attn.in_proj_b",
    "language_model.layers.16.linear_attn.conv1d",
    "language_model.layers.16.linear_attn.in_proj_a",
    "language_model.layers.16.linear_attn.in_proj_b",
    "language_model.layers.17.linear_attn.conv1d",
    "language_model.layers.17.linear_attn.in_proj_a",
    "language_model.layers.17.linear_attn.in_proj_b",
    "language_model.layers.18.linear_attn.conv1d",
    "language_model.layers.18.linear_attn.in_proj_a",
    "language_model.layers.18.linear_attn.in_proj_b",
    "language_model.layers.2.linear_attn.conv1d",
    "language_model.layers.2.linear_attn.in_proj_a",
    "language_model.layers.2.linear_attn.in_proj_b",
    "language_model.layers.20.linear_attn.conv1d",
    "language_model.layers.20.linear_attn.in_proj_a",
    "language_model.layers.20.linear_attn.in_proj_b",
    "language_model.layers.21.linear_attn.conv1d",
    "language_model.layers.21.linear_attn.in_proj_a",
    "language_model.layers.21.linear_attn.in_proj_b",
    "language_model.layers.22.linear_attn.conv1d",
    "language_model.layers.22.linear_attn.in_proj_a",
    "language_model.layers.22.linear_attn.in_proj_b",
    "language_model.layers.24.linear_attn.conv1d",
    "language_model.layers.24.linear_attn.in_proj_a",
    "language_model.layers.24.linear_attn.in_proj_b",
    "language_model.layers.25.linear_attn.conv1d",
    "language_model.layers.25.linear_attn.in_proj_a",
    "language_model.layers.25.linear_attn.in_proj_b",
    "language_model.layers.26.linear_attn.conv1d",
    "language_model.layers.26.linear_attn.in_proj_a",
    "language_model.layers.26.linear_attn.in_proj_b",
    "language_model.layers.28.linear_attn.conv1d",
    "language_model.layers.28.linear_attn.in_proj_a",
    "language_model.layers.28.linear_attn.in_proj_b",
    "language_model.layers.29.linear_attn.conv1d",
    "language_model.layers.29.linear_attn.in_proj_a",
    "language_model.layers.29.linear_attn.in_proj_b",
    "language_model.layers.30.linear_attn.conv1d",
    "language_model.layers.30.linear_attn.in_proj_a",
    "language_model.layers.30.linear_attn.in_proj_b",
    "language_model.layers.32.linear_attn.conv1d",
    "language_model.layers.32.linear_attn.in_proj_a",
    "language_model.layers.32.linear_attn.in_proj_b",
    "language_model.layers.33.linear_attn.conv1d",
    "language_model.layers.33.linear_attn.in_proj_a",
    "language_model.layers.33.linear_attn.in_proj_b",
    "language_model.layers.34.linear_attn.conv1d",
    "language_model.layers.34.linear_attn.in_proj_a",
    "language_model.layers.34.linear_attn.in_proj_b",
    "language_model.layers.36.linear_attn.conv1d",
    "language_model.layers.36.linear_attn.in_proj_a",
    "language_model.layers.36.linear_attn.in_proj_b",
    "language_model.layers.37.linear_attn.conv1d",
    "language_model.layers.37.linear_attn.in_proj_a",
    "language_model.layers.37.linear_attn.in_proj_b",
    "language_model.layers.38.linear_attn.conv1d",
    "language_model.layers.38.linear_attn.in_proj_a",
    "language_model.layers.38.linear_attn.in_proj_b",
    "language_model.layers.4.linear_attn.conv1d",
    "language_model.layers.4.linear_attn.in_proj_a",
    "language_model.layers.4.linear_attn.in_proj_b",
    "language_model.layers.40.linear_attn.conv1d",
    "language_model.layers.40.linear_attn.in_proj_a",
    "language_model.layers.40.linear_attn.in_proj_b",
    "language_model.layers.41.linear_attn.conv1d",
    "language_model.layers.41.linear_attn.in_proj_a",
    "language_model.layers.41.linear_attn.in_proj_b",
    "language_model.layers.42.linear_attn.conv1d",
    "language_model.layers.42.linear_attn.in_proj_a",
    "language_model.layers.42.linear_attn.in_proj_b",
    "language_model.layers.44.linear_attn.conv1d",
    "language_model.layers.44.linear_attn.in_proj_a",
    "language_model.layers.44.linear_attn.in_proj_b",
    "language_model.layers.45.linear_attn.conv1d",
    "language_model.layers.45.linear_attn.in_proj_a",
    "language_model.layers.45.linear_attn.in_proj_b",
    "language_model.layers.46.linear_attn.conv1d",
    "language_model.layers.46.linear_attn.in_proj_a",
    "language_model.layers.46.linear_attn.in_proj_b",
    "language_model.layers.48.linear_attn.conv1d",
    "language_model.layers.48.linear_attn.in_proj_a",
    "language_model.layers.48.linear_attn.in_proj_b",
    "language_model.layers.49.linear_attn.conv1d",
    "language_model.layers.49.linear_attn.in_proj_a",
    "language_model.layers.49.linear_attn.in_proj_b",
    "language_model.layers.5.linear_attn.conv1d",
    "language_model.layers.5.linear_attn.in_proj_a",
    "language_model.layers.5.linear_attn.in_proj_b",
    "language_model.layers.50.linear_attn.conv1d",
    "language_model.layers.50.linear_attn.in_proj_a",
    "language_model.layers.50.linear_attn.in_proj_b",
    "language_model.layers.52.linear_attn.conv1d",
    "language_model.layers.52.linear_attn.in_proj_a",
    "language_model.layers.52.linear_attn.in_proj_b",
    "language_model.layers.53.linear_attn.conv1d",
    "language_model.layers.53.linear_attn.in_proj_a",
    "language_model.layers.53.linear_attn.in_proj_b",
    "language_model.layers.54.linear_attn.conv1d",
    "language_model.layers.54.linear_attn.in_proj_a",
    "language_model.layers.54.linear_attn.in_proj_b",
    "language_model.layers.56.linear_attn.conv1d",
    "language_model.layers.56.linear_attn.in_proj_a",
    "language_model.layers.56.linear_attn.in_proj_b",
    "language_model.layers.57.linear_attn.conv1d",
    "language_model.layers.57.linear_attn.in_proj_a",
    "language_model.layers.57.linear_attn.in_proj_b",
    "language_model.layers.58.linear_attn.conv1d",
    "language_model.layers.58.linear_attn.in_proj_a",
    "language_model.layers.58.linear_attn.in_proj_b",
    "language_model.layers.6.linear_attn.conv1d",
    "language_model.layers.6.linear_attn.in_proj_a",
    "language_model.layers.6.linear_attn.in_proj_b",
    "language_model.layers.60.linear_attn.conv1d",
    "language_model.layers.60.linear_attn.in_proj_a",
    "language_model.layers.60.linear_attn.in_proj_b",
    "language_model.layers.61.linear_attn.conv1d",
    "language_model.layers.61.linear_attn.in_proj_a",
    "language_model.layers.61.linear_attn.in_proj_b",
    "language_model.layers.62.linear_attn.conv1d",
    "language_model.layers.62.linear_attn.in_proj_a",
    "language_model.layers.62.linear_attn.in_proj_b",
    "language_model.layers.8.linear_attn.conv1d",
    "language_model.layers.8.linear_attn.in_proj_a",
    "language_model.layers.8.linear_attn.in_proj_b",
    "language_model.layers.9.linear_attn.conv1d",
    "language_model.layers.9.linear_attn.in_proj_a",
    "language_model.layers.9.linear_attn.in_proj_b",
    "visual.blocks.0.attn.proj",
    "visual.blocks.0.attn.qkv",
    "visual.blocks.0.mlp.linear_fc1",
    "visual.blocks.0.mlp.linear_fc2",
    "visual.blocks.1.attn.proj",
    "visual.blocks.1.attn.qkv",
    "visual.blocks.1.mlp.linear_fc1",
    "visual.blocks.1.mlp.linear_fc2",
    "visual.blocks.10.attn.proj",
    "visual.blocks.10.attn.qkv",
    "visual.blocks.10.mlp.linear_fc1",
    "visual.blocks.10.mlp.linear_fc2",
    "visual.blocks.11.attn.proj",
    "visual.blocks.11.attn.qkv",
    "visual.blocks.11.mlp.linear_fc1",
    "visual.blocks.11.mlp.linear_fc2",
    "visual.blocks.12.attn.proj",
    "visual.blocks.12.attn.qkv",
    "visual.blocks.12.mlp.linear_fc1",
    "visual.blocks.12.mlp.linear_fc2",
    "visual.blocks.13.attn.proj",
    "visual.blocks.13.attn.qkv",
    "visual.blocks.13.mlp.linear_fc1",
    "visual.blocks.13.mlp.linear_fc2",
    "visual.blocks.14.attn.proj",
    "visual.blocks.14.attn.qkv",
    "visual.blocks.14.mlp.linear_fc1",
    "visual.blocks.14.mlp.linear_fc2",
    "visual.blocks.15.attn.proj",
    "visual.blocks.15.attn.qkv",
    "visual.blocks.15.mlp.linear_fc1",
    "visual.blocks.15.mlp.linear_fc2",
    "visual.blocks.16.attn.proj",
    "visual.blocks.16.attn.qkv",
    "visual.blocks.16.mlp.linear_fc1",
    "visual.blocks.16.mlp.linear_fc2",
    "visual.blocks.17.attn.proj",
    "visual.blocks.17.attn.qkv",
    "visual.blocks.17.mlp.linear_fc1",
    "visual.blocks.17.mlp.linear_fc2",
    "visual.blocks.18.attn.proj",
    "visual.blocks.18.attn.qkv",
    "visual.blocks.18.mlp.linear_fc1",
    "visual.blocks.18.mlp.linear_fc2",
    "visual.blocks.19.attn.proj",
    "visual.blocks.19.attn.qkv",
    "visual.blocks.19.mlp.linear_fc1",
    "visual.blocks.19.mlp.linear_fc2",
    "visual.blocks.2.attn.proj",
    "visual.blocks.2.attn.qkv",
    "visual.blocks.2.mlp.linear_fc1",
    "visual.blocks.2.mlp.linear_fc2",
    "visual.blocks.20.attn.proj",
    "visual.blocks.20.attn.qkv",
    "visual.blocks.20.mlp.linear_fc1",
    "visual.blocks.20.mlp.linear_fc2",
    "visual.blocks.21.attn.proj",
    "visual.blocks.21.attn.qkv",
    "visual.blocks.21.mlp.linear_fc1",
    "visual.blocks.21.mlp.linear_fc2",
    "visual.blocks.22.attn.proj",
    "visual.blocks.22.attn.qkv",
    "visual.blocks.22.mlp.linear_fc1",
    "visual.blocks.22.mlp.linear_fc2",
    "visual.blocks.23.attn.proj",
    "visual.blocks.23.attn.qkv",
    "visual.blocks.23.mlp.linear_fc1",
    "visual.blocks.23.mlp.linear_fc2",
    "visual.blocks.24.attn.proj",
    "visual.blocks.24.attn.qkv",
    "visual.blocks.24.mlp.linear_fc1",
    "visual.blocks.24.mlp.linear_fc2",
    "visual.blocks.25.attn.proj",
    "visual.blocks.25.attn.qkv",
    "visual.blocks.25.mlp.linear_fc1",
    "visual.blocks.25.mlp.linear_fc2",
    "visual.blocks.26.attn.proj",
    "visual.blocks.26.attn.qkv",
    "visual.blocks.26.mlp.linear_fc1",
    "visual.blocks.26.mlp.linear_fc2",
    "visual.blocks.3.attn.proj",
    "visual.blocks.3.attn.qkv",
    "visual.blocks.3.mlp.linear_fc1",
    "visual.blocks.3.mlp.linear_fc2",
    "visual.blocks.4.attn.proj",
    "visual.blocks.4.attn.qkv",
    "visual.blocks.4.mlp.linear_fc1",
    "visual.blocks.4.mlp.linear_fc2",
    "visual.blocks.5.attn.proj",
    "visual.blocks.5.attn.qkv",
    "visual.blocks.5.mlp.linear_fc1",
    "visual.blocks.5.mlp.linear_fc2",
    "visual.blocks.6.attn.proj",
    "visual.blocks.6.attn.qkv",
    "visual.blocks.6.mlp.linear_fc1",
    "visual.blocks.6.mlp.linear_fc2",
    "visual.blocks.7.attn.proj",
    "visual.blocks.7.attn.qkv",
    "visual.blocks.7.mlp.linear_fc1",
    "visual.blocks.7.mlp.linear_fc2",
    "visual.blocks.8.attn.proj",
    "visual.blocks.8.attn.qkv",
    "visual.blocks.8.mlp.linear_fc1",
    "visual.blocks.8.mlp.linear_fc2",
    "visual.blocks.9.attn.proj",
    "visual.blocks.9.attn.qkv",
    "visual.blocks.9.mlp.linear_fc1",
    "visual.blocks.9.mlp.linear_fc2",
    "visual.merger.linear_fc1",
    "visual.merger.linear_fc2",
    "visual.patch_embed.proj",
    "visual.pos_embed",
    "mtp.fc"
])
quantized_model = Qwen3_5ForConditionalGeneration.from_pretrained(model_name, dtype="auto", device_map="auto", quantization_config=quantization_config)

quant_path = "./output"
quantized_model.save_pretrained(quant_path)

# Patch safetensors: add "model." prefix to all weight keys for vLLM compatibility
# transformers saves keys as "language_model.X" but vLLM expects "model.language_model.X"
import glob, json
from safetensors.torch import load_file, save_file

for sf_path in glob.glob(f"{quant_path}/model*.safetensors"):
    tensors = load_file(sf_path)
    patched = {}
    for key, value in tensors.items():
        if not key.startswith("model.") and not key.startswith("lm_head."):
            patched[f"model.{key}"] = value
        else:
            patched[key] = value
    save_file(patched, sf_path)
    print(f"Patched {sf_path}: added model. prefix to {len(tensors)} keys")

# Patch config.json: add "model." prefix to modules_to_not_convert and fix architecture
config_path = f"{quant_path}/config.json"
with open(config_path, "r") as f:
    config = json.load(f)

config["architectures"] = ["Qwen3_5ForConditionalGeneration"]

if "quantization_config" in config and "modules_to_not_convert" in config["quantization_config"]:
    config["quantization_config"]["modules_to_not_convert"] = [
        f"model.{name}" if not name.startswith("model.") else name
        for name in config["quantization_config"]["modules_to_not_convert"]
    ]

with open(config_path, "w") as f:
    json.dump(config, f, indent=2)
print("Patched config.json: architecture + modules_to_not_convert prefixes")

# print(quantized_model)