model: Qwen/Qwen3.5-0.8B
output_dir: ./reverse-fft
merge_adapter: true

per_device_train_batch_size: 2
gradient_accumulation_steps: 16

sample_packing: true
sequence_len: 4096
save_steps: 0

max_steps: 100
eval_steps: 25

learning_rate: 2e-4

recipe: fp8-hybrid
warmup_ratio: 0.15

lora: true
lora_rank: 16
lora_alpha: 32
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

dataloader_num_workers: 4
datasets:
  - path: "willcb/R1-reverse-wikipedia-paragraphs-v1-1000"
    type: conversation
    messages_field: prompt
    completion_field: completion
